name = "Pizza Dumpster"
author = "smumfy"
version = "3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c90c80021eb015ca6127936e5bb91e815157e83cbf6e7102111f7080a07f639"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
