name = "Pizza Dumpster"
author = "smumfy"
version = "3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "450a356a2ae5136bb2a55351dbf6121189adbd404b0de63d239c67bb80097a71"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
