name = "Pizza Dumpster"
author = "smumfy"
version = "3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5621f7e719e3ade6856a3d1bc53108c5b266fa7dee89fa21be4295393d4c69f8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
