name = "Pizza Dumpster"
author = "smumfy"
version = "3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48e0cfe55527e990e1238bc80c0c92bde9e787345db83d7cd19ed7e733c40a7f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
